require("after.plugin.colors")
require("after.plugin.lualine")
require("after.plugin.nvim-tree")
require("after.plugin.telescope")
require("after.plugin.treesitter")
require("after.plugin.noice")
require("after.plugin.lsp")
require("after.plugin.barbar")
require("after.plugin.alpha-nvim")
require("luasnip.loaders.from_vscode").lazy_load()

